# .github/dependabot.yml
# Dependabot configuration file
# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot for details

version: 2

updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
