# Workflow to generate and commit a sitemap
name: Generate a sitemap

on:
  # Run the workflow at the end of every week
  schedule:
    - cron: '0 0 * * 0'
  # Run the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  # Generate a sitemap and commit it to the repository
  generate-sitemap:
    name: Generate and commit a sitemap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pdfo.github.io
        uses: actions/checkout@v3
        with:
          # Set the main branch for the git-auto-commit-action action
          # It is otherwise undefined for any non-push event
          ref: ${{ github.head_ref }}
          # Ensure that the generate-sitemap action has access to the commit history
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://www.pdfo.net/

      - name: Output statistics
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Check for changes
        # The storage and the commit are triggered only if the sitemap changed
        run: |
          echo "status=$(git status --porcelain sitemap.xml)" >> $GITHUB_ENV

      - name: Store artifacts
        if: ${{ env.status }}
        uses: actions/upload-artifact@v3
        with:
          path: ./sitemap.xml

      - name: Commit the sitemap
        if: ${{ env.status }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update sitemap.xml
          file_pattern: sitemap.xml
          repository: .
          commit_user_name: pdfo
          commit_user_email: pdfocode@gmail.com
          commit_author: PDFO <pdfocode@gmail.com>
          skip_dirty_check: true
