# Workflow to get download count statistics
name: Get download counts

on:
  # Run the workflow at the end of every day
  schedule:
    - cron: '0 0 * * *'
  # Run the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  # Generate the statistics in JSON format
  get-stats:
    name: Get the statistics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pdfo.github.io
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        # January 12, 2022: the GitHub actions setup-python upgraded the
        # default Python to v3.10 and the requirements cannot be easily met
        # with this version. We enforce the Python version to v3.9 for the
        # moment, waiting for official wheels distributions to be released in
        # newer versions. As of today:
        #   - fastparquet wheels are not available.
        with:
          python-version: '3.9'

      - name: Set environment variables
        run: |
          echo "stats_json=stats.json" >> $GITHUB_ENV
          echo "archive_conda=archive_conda.json" >> $GITHUB_ENV
          echo "archive_pypi=archive_pypi.json" >> $GITHUB_ENV
          echo "archive_github=archive_github.json" >> $GITHUB_ENV

      - name: Generate statistics
        id: statistics
        run: |
          python -m venv venv
          source venv/bin/activate
          cd static/scripts/stats/
          python -m pip install -r requirements.txt
          python counts.py ${{ env.stats_json }} ${{ env.archive_conda }} ${{ env.archive_pypi }} ${{ env.archive_github }}
          cat ${{ env.stats_json }}

      - name: Commit the statistics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update ${{ env.stats_json }}
          commit_options: '--no-verify --signoff'
          status_options: '--untracked-files=no'
          add_options: '-u'
          push_options: '--force'
          skip_dirty_check: true
