# Workflow to get download count statistics
name: Get download counts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Run the workflow at the end of every day
  schedule:
    - cron: '0 0 * * *'
  # Run the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  # Generate the statistics in JSON format
  get-stats:
    name: Get the statistics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pdfo.github.io
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Set the dump file
        run: |
          echo "file_path=./static/scripts/stats" >> $GITHUB_ENV
          echo "file_name=stats.json" >> $GITHUB_ENV

      - name: Generate statistics
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r ./static/scripts/stats/requirements.txt
          python ./static/scripts/stats/counts.py ${{ env.file_path }}/${{ env.file_name }}

      - name: Commit the statistics
        run: |
          git config user.name "pdfo"
          git config user.email "pdfocode@gmail.com"
          git pull origin master
          if [[ ! -z "$(git status --porcelain ${{ env.file_path }}/${{ env.file_name }})" ]]; then
              git add ${{ env.file_path }}/${{ env.file_name }}
              git commit -m "Update ${{ env.file_name }}"
              git push origin master
          fi